#!/bin/bash

function mike {
    make ARCH=arm clean
    make ARCH=arm xbones_crespo4g_defconfig
    make -j3 ARCH=arm CROSS_COMPILE=arm-eabi-
}

function crossbones {
    make ARCH=arm clean
    make ARCH=arm xbones_crespo4g_defconfig
    make -j32 ARCH=arm CROSS_COMPILE=arm-eabi-
}

if [ $USER = "mike" ]; then
    export PATH=$PATH:/home/$USER/android/Crossbones/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/
    mike
elif [ $USER = "crossbones" ]; then
    export PATH=$PATH:/home/$USER/Crossbones/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/
    crossbones
else
    echo "This script is not built for your user"
fi
